### ISSUE TITLE
Feature Request: Add cachepath input

### ISSUE THREAD

**Issue by caveman8fb** [sysdiglabs/sysdig-azure-devops-task#5]
**What**
Add an optional input to set the cachepath value.

**Why**
So that the -p or --cachepath value can be passed via Azure DevOps Pipelines

This is useful for agents that do not have enough space in /tmp which the cache defaults to for large container images.

**Example**
```
- task: Sysdig-CLI-Scan@1
  displayName: Sysdig CLI Scan
  inputs:
    sysdigurl: 'https://app.us4.sysdig.com'
    apikey: $(SYSDIG_API_TOKEN)
    image: $(imageName)
    jsonOutput: true
    jsonOutputFile: 'sysdig-cli-scan-output.json'
    cachePath: /opt/sysdigtemp
```
